<%
Response.Write "<!DOCTYPE html>"
Response.Write "<html>"
Response.Write "<head>"
Response.Write "    <style type=""text/css"">"
Response.Write "        table {"
Response.Write "            width: 100%;"
Response.Write "            border-collapse: collapse;"
Response.Write "        }"
Response.Write "        td {"
Response.Write "            border: 1px solid black;"
Response.Write "            padding: 6px;"
Response.Write "        }"
Response.Write "        input[type=""text""] {"
Response.Write "            width: 100%; "
Response.Write "            outline: none;"
Response.Write "            border: none;"
Response.Write "        }"
Response.Write "        button{"
Response.Write "            margin-top: 5px;"
Response.Write "            padding: 10px 20px;"
Response.Write "            color: aliceblue;"
Response.Write "            background-color: black;"
Response.Write "        }"
Response.Write "        textarea{"
Response.Write "            width: 100%;"
Response.Write "            height:75px;"
Response.Write "            outline: none;"
Response.Write "            border: none;"
Response.Write "        }"
Response.Write ""
Response.Write "    </style>"
Response.Write "</head>"
Response.Write "    <body>"
Response.Write "        <h2><b><u>1.Medical Certificate</u></b></h2>"
Response.Write "        <table>"
Response.Write "            <tr>"
Response.Write "                <td> </td>  "
Response.Write "                <td colspan=""10""><b><u>Medical Cerificate</u></b></td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td > I hear by certify that I have Examined:</td>"
Response.Write "                <td> Test Examinee </td>"
Response.Write "                <td> AGE</td>"
Response.Write "                <td> 75</td>"
Response.Write "                <td> WEIGHT</td>"
Response.Write "                <td colspan=""4""> 85</td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td colspan=""10""> I Find that:</td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> General Physique</td>"
Response.Write "                <td colspan=""5""> Normal</td>"
Response.Write "                <td> Comments:</td>"
Response.Write "                <td ><input type=""text"" id=""c1""> </td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> Skeletal System</td>"
Response.Write "                <td colspan=""5""> Abnormal </td>"
Response.Write "                <td > Comments:</td>"
Response.Write "                <td ><input type=""text""  id=""c2""> </td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> Chest Lungs & Heart: </td>"
Response.Write "                <td colspan=""5""> Normal</td>"
Response.Write "                <td > Comments:</td>"
Response.Write "                <td ><input type=""text"" id=""c3""> </td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> BP: </td>"
Response.Write "                <td colspan=""2""> 120/82 </td>"
Response.Write "                <td> Pulse </td>"
Response.Write "                <td colspan=""2""> 85 </td>"
Response.Write "                <td > Comments:</td>"
Response.Write "                <td ><input type=""text"" id=""c4""> </td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> Abdomen:</td>"
Response.Write "                <td colspan=""5""> Normal</td>"
Response.Write "                <td > Comments:</td>"
Response.Write "                <td ><input type=""text"" id=""c5""> </td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td colspan=""3""> Hernia</td>"
Response.Write "                <td colspan=""3""> Normal</td>"
Response.Write "                <td > Comments:</td>"
Response.Write "                <td ><input type=""text"" id=""c6""> </td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> Uro-Genital System</td>"
Response.Write "                <td colspan=""5""> Abnormal</td>"
Response.Write "                <td > Comments:</td>"
Response.Write "                <td ><input type=""text"" id=""c7""> </td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> Ear-Nose Throat:</td>"
Response.Write "                <td colspan=""5""> Abnormal</td>"
Response.Write "                <td > Comments:</td>"
Response.Write "                <td ><input type=""text"" id=""c8""> </td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td colspan=""3""> Vision</td>"
Response.Write "                <td colspan=""3""> 6/6</td>"
Response.Write "                <td > Comments:</td>"
Response.Write "                <td ><input type=""text"" id=""c9""> </td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> Eyes:</td>"
Response.Write "                <td colspan=""5""></td>"
Response.Write "                <td > Comments:</td>"
Response.Write "                <td ><input type=""text"" id=""c10""> </td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> Skin:</td>"
Response.Write "                <td colspan=""5""> Normal</td>"
Response.Write "                <td > Comments:</td>"
Response.Write "                <td ><input type=""text"" id=""c11""> </td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td colspan=""3""> Nervous System:</td>"
Response.Write "                <td colspan=""3""> Strong</td>"
Response.Write "                <td > Comments:</td>"
Response.Write "                <td ><input type=""text"" id=""c12""> </td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> Teeth:</td>"
Response.Write "                <td colspan=""5""> Normal</td>"
Response.Write "                <td > Comments:</td>"
Response.Write "                <td ><input type=""text"" id=""c13""> </td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> RUST:</td>"
Response.Write "                <td colspan=""5""> Normal</td>"
Response.Write "                <td> Comments:</td>"
Response.Write "                <td ><input type=""text"" id=""c14""> </td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td colspan=""6""> <b><u>Cardiovascular System:</u></b></td>"
Response.Write "                <td colspan=""3"" align=""center""> <b>Comments</b></td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> Pulse Rate: </td>"
Response.Write "                <td colspan=""2""> 120/82 </td>"
Response.Write "                <td> Rhythm </td>"
Response.Write "                <td colspan=""2""> Regular </td>"
Response.Write "                <td colspan=""3"" rowspan=""4""><textarea id=""c15""></textarea></td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> Volume: </td>"
Response.Write "                <td colspan=""2""> Good </td>"
Response.Write "                <td> Collapsing </td>"
Response.Write "                <td colspan=""2""> Yes </td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> BP (mmHg) </td>"
Response.Write "                <td colspan=""3""> Good </td>"
Response.Write "                <td>Apex Beat </td>"
Response.Write "                <td> Normal</td> "
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> Heart Sounds </td>"
Response.Write "                <td colspan=""2""> 3rd Heart sound </td>"
Response.Write "                <td> Others </td>"
Response.Write "                <td colspan=""2""> Having been having severe pain </td>  "
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td colspan=""6""> <b><u>Respiratory System:</u></b></td>"
Response.Write "                <td colspan=""3"" align=""center""> <b>Comments</b></td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> Inspection </td>"
Response.Write "                <td colspan=""2""> I realised that the heart was beating very fast</td>"
Response.Write "                <td> Palpation</td>"
Response.Write "                <td colspan=""2""> Having been having severe pain </td>"
Response.Write "                <td colspan=""3"" rowspan=""3""><textarea id=""c16""></textarea></td>"
Response.Write "            </tr>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> Purcussion Note</td>"
Response.Write "                <td colspan=""2""> Dull</td>"
Response.Write "                <td> Others</td>"
Response.Write "                <td colspan=""2""> Having been having severe pain </td>"
Response.Write "            </tr>"
Response.Write "                <td> </td>"
Response.Write "                <td> Auscultation </td>"
Response.Write "                <td colspan=""2""> Air Entry </td>"
Response.Write "                <td> Absent</td>"
Response.Write "                <td> Others</td>"
Response.Write "                <td> Dull </td>"
Response.Write "            <tr>"
Response.Write "                <td> </td>"
Response.Write "                <td colspan=""10""><b>FINAL STATUS: </b>"
Response.Write "                    <select id=""selectBox"" name=""finalStatus"">"
Response.Write "                    <option value=""NULL""> </option>"
Response.Write "                    <option value=""UNFIT"">UNFIT</option>"
Response.Write "                    <option value=""FIT"">FIT</option>"
Response.Write "                    <option value=""REVIEW"">REVIEW</option>"
Response.Write "                    <option value=""REFER TO SPECIALIST"">REFER TO SPECIALIST</option>"
Response.Write "                </select>"
Response.Write "                </td>     "
Response.Write "            </tr>"
Response.Write "            </table>"
Response.Write "        <button onclick=""addToArray()"">Save</button>"
Response.Write ""
Response.Write "        <p>Comments: <span id=""commentValues""></span></p>"
Response.Write ""
Response.Write vbCrLf & "        <script>    "
Response.Write vbCrLf & "     var valueArray = [];"
Response.Write vbCrLf & "        function addToArray() {"
Response.Write vbCrLf & "            for (var i = 1; i <= 16; i++) {"
Response.Write vbCrLf & "                var inputElement = document.getElementById(""c"" + i);"
Response.Write vbCrLf & "                var textValue = inputElement.value.trim();"
Response.Write vbCrLf & "                "
Response.Write vbCrLf & "                if (textValue !== """") {"
Response.Write vbCrLf & "                    var elementId = inputElement.id"
Response.Write vbCrLf & "                    valueArray.push(elementId +""**""+textValue);"
Response.Write vbCrLf & "                    inputElement.value = """";"
Response.Write vbCrLf & "                }   "
Response.Write vbCrLf & "            }"
Response.Write vbCrLf & "                var selectElement = document.getElementById(""selectBox"")"
Response.Write vbCrLf & "                var selectValue = selectElement.value"
Response.Write vbCrLf & "                var selectId = selectElement.id"
Response.Write vbCrLf & "                valueArray.push(selectId +""**""+selectValue)"
Response.Write vbCrLf & "                selectElement.value="""";"
Response.Write vbCrLf & "                "
Response.Write vbCrLf & "            document.getElementById(""commentValues"").textContent = valueArray.join(""||"");"
Response.Write vbCrLf & "        }"
Response.Write vbCrLf & "        </script>"
Response.Write "    </body>"
Response.Write "</html>"
%>